# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  global_variable: "${{Build.SourceBranch}}"

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $(global_variable)

# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     useGlobalJson: true

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     includesymbols: true
#     versioningScheme: 'off'

# - publish: '$(Build.ArtifactStagingDirectory)'

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your PowerShell commands here.
      
#       Write-Host "${{Build.SourceBranch}}"
#     pwsh: true

