# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  isMasterBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isReleaseBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $(isMasterBranch)
- bash: echo $(isReleaseBranch)

# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     useGlobalJson: true

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     includesymbols: true
#     versioningScheme: 'off'

# - publish: '$(Build.ArtifactStagingDirectory)'

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your PowerShell commands here.
      
#       Write-Host "${{Build.SourceBranch}}"
#     pwsh: true

